name: CI Workflow for Angular

on:
  push:
    branches:
      - test-prod
  pull_request:
    branches:
      - test-prod

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Verificar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Configurar o Node.js e o ambiente do Angular
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Passo 3: Instalar as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Passo 4: Rodar o servidor de desenvolvimento
      - name: Run Angular development server
        run: npm run start -- --host 0.0.0.0 --port 4200 --proxy-config proxy.conf.js &

      # Passo 5: Verificar se o servidor está funcionando (Health Check)
      - name: Health Check for Angular server
        run: |
          sleep 30  # Espera o servidor Angular iniciar
          curl --silent --fail http://localhost:4200 || exit 1  # Verifica se o servidor responde na porta 4200
